apiVersion: v1
kind: Secret
metadata:
  name: django-secret
  namespace: <namespace>
type: Opaque
data:
  DEBUG: <base64-encoded-debug>
  SECRET_KEY: <base64-encoded-secret_key>
  ALLOWED_HOSTS: <base64-encoded-hosts>
  DATABASE_URL: <base64-encoded-db_url>