apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: edu-jovial-mclean
  labels:
    app: nginx
spec:
  restartPolicy: OnFailure
  containers:
    - name: nginx
      image: nginx:stable-perl
      ports:
        - containerPort: 80


