apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: edu-jovial-mclean
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - name: http
      nodePort: 30381
      protocol: TCP
      port: 80
      targetPort: 80
